services:
  web:
    build: .
    container_name: cas_exam_app
    ports:
      - "8000:8000"
    volumes:
      - cas_sqlite_data:/app
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=cas-exam-production-secret-key-301students
      - ADMIN_USERNAME=ADMIN01
      - ADMIN_PASSWORD=AdminPassword123!
      - STUDENT_PASSWORD=StudentPass123!
    restart: unless-stopped

volumes:
  cas_sqlite_data:
