# Generated by Django 6.0 on 2026-10-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questions_per_attempt',
            field=models.PositiveIntegerField(default=30, help_text='Number of questions randomly selected per attempt'),
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='core.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='core.question')),
            ],
            options={
                'ordering': ['question_order', 'id'],
                'unique_together': {('attempt', 'question'), ('attempt', 'question_order')},
            },
        ),
    ]
