# Generated by Django 6.0 on 2026-10-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exam_questions_per_attempt_attemptquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
