# Generated by Django 6.0 on 2026-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_explanation_question_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_violations',
            field=models.PositiveIntegerField(default=6, help_text='Maximum allowed integrity violations before auto-submission (recommended: 5-7)'),
        ),
    ]
