# Generated by Django 6.0 on 2026-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exam_max_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Quiz'), ('CODING', 'Coding / Practical Assignment')], default='MCQ', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('CODING', 'Coding / Practical Question')], default='MCQ', max_length=20),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
    ]
