# Generated by Django 6.0 on 2026-10-07 17:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_exam_type_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.student_submission_upload_path),
        ),
    ]
